server.port=${SERVER_PORT}
spring.application.name=etransparencia-api-user
spring.application.version=3.3.0-SNAPSHOT
server.servlet.context-path=/v1/api
spring.jpa.open-in-view: false
spring.application.default-username=${ADMIN_USERNAME}
spring.application.default-email=${ADMIN_EMAIL}
spring.application.default-password=${ADMIN_PASSWORD}

origin.url=${ORIGIN_URL}
user.api.url=${USER_API_URL}
jwt.secret.key=${SECRET_KEY}
jwt.expiration.time=${EXP_TIME}
transparencia.api.key=${API_KEY}
spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URI}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.pool-name=TransparenciaHikariCP
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED
logging.level.org.hibernate.orm.connections.pooling=WARN

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000