spring:
  datasource:
    url: ${DB_URI:uri}/${DB_NAME:name}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:usr}
    password: ${DB_PASS:pass}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 55MB