server.port=${SERVER_PORT:port}
spring.application.name=transparencia-api
spring.datasource.url=${DB_URI:uri}/${DB_NAME:name}
spring.datasource.username=${DB_USER:usr}
spring.datasource.password=${DB_PASS:pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=55MB
jwt.secret.key=${SECRET_KEY:key}
jwt.expiration.time=${EXP_TIME:exp}
spring.application.default-username=${ADMIN_USERNAME:user}
spring.application.default-email=${ADMIN_EMAIL:email}
spring.application.default-password=${ADMIN_PASSWORD:password}
spring.mail.host=${MAIL_HOST:mhost}
spring.mail.port=${MAIL_PORT:mport}
spring.mail.username=${MAIL_USER:muser}
spring.mail.password=${MAIL_PASS:mpass}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
